### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by scarlettvalentin** [learn-co-curriculum/dsc-polynomial-regression-v2-5#1]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ x] Other (explain below)

### Source

```
Additional Resources
Check out [this resource](https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:quadratic-functions-equations) for a refresher on parabolas and the relationship between quadratic graphs and formulas
Wondering why we always seem to use every lower degree term instead of skipping to a higher degree? [This resource](https://maxhfarrell.com/bus41100/handout_41100_PolynomialRegression.pdf) demonstrates how that would be similar to skipping the intercept term and involve making undue assumptions
```

### Concern

When I click the second link, the new window states "Not Found
The requested URL was not found on this server."

## What OS Are You Using?

- [x ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for letting us know. Generally, we remove bad links when they are flagged. Again, appreciate we appreciate you taking the time to flag this.

**Comment by bpurdy-ds** [comment]
Removed. Thank you again.
